# Generated by Django 5.1.4 on 2025-02-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classeGrammaticale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClasseNominale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotEton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_eton', models.CharField(max_length=200)),
                ('pluriel', models.CharField(blank=True, max_length=200, null=True)),
                ('sens_litteral', models.TextField(blank=True, null=True)),
                ('prononciation', models.FileField(blank=True, null=True, upload_to='audios/mots/')),
                ('class_grammaticale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mots_eton', to='dictionnaire.classegrammaticale')),
                ('classe_nominale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mots_eton', to='dictionnaire.classenominale')),
                ('mot_reference', models.ManyToManyField(blank=True, related_name='references', to='dictionnaire.moteton')),
                ('synonyme', models.ManyToManyField(blank=True, to='dictionnaire.moteton')),
            ],
        ),
        migrations.CreateModel(
            name='Traduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_francais', models.CharField(max_length=200)),
                ('definition', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/mots/')),
                ('phrase_eton', models.TextField(blank=True, null=True)),
                ('phrase_francais', models.TextField(blank=True, null=True)),
                ('prononciation', models.FileField(blank=True, null=True, upload_to='audios/phrase/')),
                ('mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traductions', to='dictionnaire.moteton')),
            ],
        ),
    ]
