# Generated by Django 5.1.4 on 2025-02-20 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_francais', models.CharField(max_length=200, unique=True)),
                ('mot_eton', models.CharField(max_length=200)),
                ('prononciation', models.FileField(blank=True, null=True, upload_to='audios/mots/')),
            ],
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_francais', models.TextField()),
                ('traduction_eton', models.TextField()),
                ('pronociation', models.FileField(blank=True, null=True, upload_to='audios/expressions/')),
                ('mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='dictionnaire.mot')),
            ],
        ),
    ]
