# Generated by Django 5.1.4 on 2025-02-23 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traduction',
            name='phrase_eton',
        ),
        migrations.RemoveField(
            model_name='traduction',
            name='phrase_francais',
        ),
        migrations.RemoveField(
            model_name='traduction',
            name='prononciation',
        ),
        migrations.CreateModel(
            name='Exemple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_eton', models.TextField()),
                ('phrase_francais', models.TextField()),
                ('prononciation', models.FileField(blank=True, null=True, upload_to='audios/exemples/')),
                ('traduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemples', to='dictionnaire.traduction')),
            ],
        ),
    ]
