# Generated by Django 5.1.4 on 2025-02-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classeGrammaticale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='expression',
            old_name='pronociation',
            new_name='prononciation',
        ),
        migrations.AddField(
            model_name='mot',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/mots/'),
        ),
        migrations.AddField(
            model_name='mot',
            name='mot_reference',
            field=models.ManyToManyField(blank=True, related_name='references', to='dictionnaire.mot'),
        ),
        migrations.AddField(
            model_name='mot',
            name='pluriel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mot',
            name='class_grammaticale',
            field=models.ManyToManyField(related_name='mots', to='dictionnaire.classegrammaticale'),
        ),
    ]
