# Generated by Django 5.1.4 on 2025-02-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0002_classegrammaticale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mot',
            name='class_grammaticale',
        ),
        migrations.RemoveField(
            model_name='mot',
            name='mot_reference',
        ),
        migrations.CreateModel(
            name='MotEton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_eton', models.CharField(max_length=200)),
                ('pluriel', models.CharField(blank=True, max_length=200, null=True)),
                ('prononciation', models.FileField(blank=True, null=True, upload_to='audios/mots/')),
                ('class_grammaticale', models.ManyToManyField(related_name='mots', to='dictionnaire.classegrammaticale')),
                ('mot_reference', models.ManyToManyField(blank=True, related_name='references', to='dictionnaire.moteton')),
            ],
        ),
        migrations.CreateModel(
            name='Traduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_francais', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/mots/')),
                ('phrase_eton', models.TextField()),
                ('phrase_francais', models.TextField()),
                ('prononciation', models.FileField(blank=True, null=True, upload_to='audios/phrase/')),
                ('mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traduction', to='dictionnaire.moteton')),
            ],
        ),
        migrations.DeleteModel(
            name='Expression',
        ),
        migrations.DeleteModel(
            name='Mot',
        ),
    ]
