# Generated by Django 5.1.4 on 2025-02-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0003_remove_mot_class_grammaticale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moteton',
            name='synonyme',
            field=models.ManyToManyField(blank=True, to='dictionnaire.moteton'),
        ),
        migrations.AlterField(
            model_name='classegrammaticale',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traduction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traduction',
            name='phrase_eton',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traduction',
            name='phrase_francais',
            field=models.TextField(blank=True, null=True),
        ),
    ]
