# Generated by Django 5.1.4 on 2025-02-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0004_moteton_synonyme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moteton',
            name='mot_eton',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
