# Generated by Django 5.1.4 on 2025-02-22 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0005_alter_moteton_mot_eton'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseNominale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='traduction',
            old_name='description',
            new_name='definition',
        ),
        migrations.RemoveField(
            model_name='moteton',
            name='class_grammaticale',
        ),
        migrations.AlterField(
            model_name='moteton',
            name='mot_eton',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='traduction',
            name='mot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traductions', to='dictionnaire.moteton'),
        ),
        migrations.AddField(
            model_name='moteton',
            name='classe_nominale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mots_eton', to='dictionnaire.classenominale'),
        ),
        migrations.AddField(
            model_name='moteton',
            name='class_grammaticale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mots_eton', to='dictionnaire.classegrammaticale'),
        ),
    ]
